#!/bin/sh
for f in $(git diff --name-only --cached); do
    if [ "`echo $f | rev | cut -d'.' -f1 | rev`" = "ipynb" ]; then
        has_content="$(cat $f | grep execution_count | grep -v ': null,')"
        if [ -n "$has_content" ]; then
            echo
            echo "    Notebook output cells need to be cleaned in: $f!"
            echo
            exit 1
        fi
    fi
done
